apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-crds
    repoURL: "https://helm.linkerd.io/stable"
    targetRevision: 1.16.1
    helm:
      releaseName: linkerd-crds
  destination:
    server: "https://kubernetes.default.svc"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: "https://helm.linkerd.io/stable"
    targetRevision: 1.16.1
    helm:
      releaseName: linkerd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkerd