apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-crds
    repoURL: "https://helm.linkerd.io/stable"
    targetRevision: 1.4.0
    helm:
      releaseName: linkerd-crds
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: "https://helm.linkerd.io/stable"
    targetRevision: 1.9.3
    helm:
      releaseName: linkerd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true